kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: aivia-barnetrygd-vedtak
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: ghcr.io/nais/aivia:latest
  liveness:
    path: /internal/isalive
    initialDelay: 20
  readiness:
    path: /internal/isready
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /internal/prometheus
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  env:
    - name: LOG_FORMAT
      value: logstash
    - name: AIVIA_TOPIC_MAPPING_PATH
      value: aivia-barnetrygd-vedtak-topic-mapping
  envFrom:
    - secret: aivia-kafka-on-prem
  filesFrom:
    - configmap: aivia-barnetrygd-vedtak-topic-mapping
  kafka:
    pool: {{pool}}