kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: familie-ba-kafka-manager
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: ghcr.io/navikt/kafka-manager/kafka-manager:2.2021.12.17_13.09-1e4eaff6c45c # See https://github.com/navikt/kafka-manager/packages
  port: 8080
  webproxy: true
  ingresses:
    - https://familie-ba-kafka-manager.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  vault:   # Optional. Required for on-prem (the env variables SERVICE_USER_NAME, SERVICE_USER_PASSWORD can also be used)
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvfamilie-ba-konsum
        mountPath: /var/run/secrets/nais.io/service_user
  azure: # Required
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 3d718ae5-f25e-47a4-b4b3-084a97604c1d # forvaltning
  kafka: # Optional. Required for Aiven
    pool: nav-dev
  env:
    - name: ON_PREM_KAFKA_BROKERS_URL
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "aapen-barnetrygd-saksstatistikk-sak-v1",
              "location": "ON_PREM",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "aapen-barnetrygd-saksstatistikk-behandling-v1",
              "location": "ON_PREM",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamfamilie.aapen-barnetrygd-vedtak-v2",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamfamilie.aapen-familie-ba-sak-opphoer-barnetrygd",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamfamilie.aapen-barnetrygd-saksstatistikk-sak-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "teamfamilie.aapen-barnetrygd-saksstatistikk-behandling-v1",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
        
          ]
        }