apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-statistikk
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8093
  liveness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvfamilie-ba-konsum
        mountPath: /var/run/secrets/srvfamilie-ba-konsum
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://familie-ba-statistikk.dev.adeo.no
    - https://familie-ba-statistikk.dev.intern.nav.no
    - https://familie-ba-statistikk.dev-fss-pub.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-ba-sak-lokal
          namespace: teamfamilie
          cluster: dev-fss
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b # teamfamilie-forvaltning
          - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
      tenant: trygdeetaten.no
      replyURLs:
        - "https://familie-ba-statistikk.dev.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  webproxy: true
  kafka:
    pool: nav-dev
