apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-statistikk
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8093
  liveness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvfamilie-ba-konsum
        mountPath: /var/run/secrets/srvfamilie-ba-konsum
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://familie-ba-statistikk.nais.adeo.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: CREDENTIAL_USERNAME
      value: /var/run/secrets/srvfamilie-ba-konsum/username
    - name: CREDENTIAL_PASSWORD
      value: /var/run/secrets/srvfamilie-ba-konsum/password
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
  webproxy: true

