apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-statistikk
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8093
  liveness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvfamilie-ba-konsum
        mountPath: /var/run/secrets/srvfamilie-ba-konsum
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://familie-ba-statistikk.intern.nav.no
    - https://familie-ba-statistikk.prod-fss-pub.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: CREDENTIAL_USERNAME
      value: /var/run/secrets/srvfamilie-ba-konsum/username
    - name: CREDENTIAL_PASSWORD
      value: /var/run/secrets/srvfamilie-ba-konsum/password
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: prod-gcp
    outbound:
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: prod-gcp
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: 3d718ae5-f25e-47a4-b4b3-084a97604c1d # teamfamilie-forvaltning
          - id: 87190cf3-b278-457d-8ab7-1a5c55a9edd7 # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 tilgang til prosessering
      replyURLs:
        - "https://familie-ba-statistikk.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  webproxy: true
  kafka:
    pool: nav-prod

