apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-vedtak-consumer
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8093
  liveness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvfamilie-ba-konsum
        mountPath: /var/run/secrets/srvfamilie-ba-konsum
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: CREDENTIAL_USERNAME
      value: /var/run/secrets/srvfamilie-ba-konsum/username
    - name: CREDENTIAL_PASSWORD
      value: /var/run/secrets/srvfamilie-ba-konsum/password
