no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

spring:
  kafka:
    bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    properties:
      schema.registry.url: http://kafka-schema-registry.tpa:8081
  datasource:
    url: jdbc:postgresql://A01DBVL020.adeo.no:5432/familie-ba-statistikk

rolle:
  teamfamilie:
    forvalter: "3d718ae5-f25e-47a4-b4b3-084a97604c1d"


