spring:
  kafka:
    bootstrap-servers: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    properties:
      schema.registry.url: http://kafka-schema-registry.tpa:8081
    consumer:
      group-id: gcp
  datasource:
    url: jdbc:postgresql://localhost:5432/familie-ba-statistikk
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}