spring:
  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    properties:
      schema.registry.url: https://kafka-schema-registry.nais.preprod.local
    consumer:
      group-id: gcp
  datasource:
    url: jdbc:postgresql://localhost:5432/familie-ba-statistikk
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}