spring:
  datasource:
    url: jdbc:postgresql://A01DBVL020.adeo.no:5432/familie-ba-statistikk

rolle:
  teamfamilie:
    forvalter: "3d718ae5-f25e-47a4-b4b3-084a97604c1d"

BA_SAK_SCOPE: api://prod-gcp.teamfamilie.familie-ba-sak/.default
BA_SAK_API_URL: https://familie-ba-sak.intern.nav.no/api
