spring:
  kafka:
    bootstrap-servers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    properties:
      schema.registry.url: https://kafka-schema-registry.nais.preprod.local
  datasource:
    url: jdbc:postgresql://b27dbvl022.preprod.local:5432/familie-ba-statistikk

rolle:
  teamfamilie:
    forvalter: "928636f4-fd0d-4149-978e-a6fb68bb19de"

BA_SAK_SCOPE: api://dev-gcp.teamfamilie.familie-ba-sak/.default
BA_SAK_API_URL: https://familie-ba-sak.dev.intern.nav.no/api



