ALTER TABLE SAKSSTATISTIKK_DVH
    ADD COLUMN FUNKSJONELL_ID VARCHAR;

UPDATE SAKSSTATISTIKK_DVH SET FUNKSJONELL_ID = CONCAT( json ->> 'fagsakId', '-', json ->> 'behandlingsId', '-', offset_verdi);

ALTER TABLE SAKSSTATISTIKK_DVH
    ALTER COLUMN FUNKSJONELL_ID set not null;