name: Build-Deploy-Preprod
on:
  workflow_dispatch:
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/familie-ba-statistikk:${{ github.sha }}
  IMAGE_LATEST: docker.pkg.github.com/${{ github.repository }}/familie-ba-statistikk:latest
jobs:
  deploy:
    name: Bygg app/image, push til github, deploy til dev-fss/prod-fss
    runs-on: ubuntu-latest
    permissions:
      packages: write
      checks: write
      contents: read
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1.0.13
      - name: Bygg Docker image og push til Github Package
        if: github.triggering_actor != 'dependabot[bot]'
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE} -t ${IMAGE_LATEST} .
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_USERNAME" --password-stdin docker.pkg.github.com
          docker push ${IMAGE}
      - name: Deploy til dev-fss
        if: github.triggering_actor != 'dependabot[bot]'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: app-preprod.yaml
