name: "Deploy aivia"

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy aivia-barnetrygd-vedtak til prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .github/aivia-vedtak-topic-configmap.yaml,.github/aivia-vedtak-topic-prod.yaml